# Generated by Django 6.1.2 on 2026-10-07 02:10

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

from apps.core.rls import EnableTenantRLS


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('display_name', models.CharField(max_length=120, verbose_name='nombre')),
                ('alias', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.barbershop')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='barbers', to='tenancy.branch')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('membership', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='barber', to='tenancy.membership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto fijo')], max_length=12, verbose_name='tipo')),
                ('value', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='valor')),
                ('valid_from', models.DateTimeField(verbose_name='vigente desde')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_rules', to='staff.barber')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.barbershop')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_rules', to='catalog.service')),
            ],
            options={
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['barber', 'service', 'valid_from'], name='staff_commi_barber__e9d13b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('commission_type__in', ['percentage', 'fixed'])), name='ck_commissionrule_type_valid'), models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='ck_commissionrule_value_not_negative'), models.CheckConstraint(condition=models.Q(('commission_type', 'fixed'), ('value__lte', 100), _connector='OR'), name='ck_commissionrule_percentage_max_100', violation_error_message='Un porcentaje de comisión no puede ser mayor que 100.')],
            },
        ),
        EnableTenantRLS("staff_barber"),
        EnableTenantRLS("staff_commissionrule"),
    ]
