# Generated by Django 6.1.2 on 2026-10-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='referencia'),
        ),
    ]
