# Generated by Django 6.1.2 on 2026-10-09 05:43

import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.core.rls import EnableTenantRLS


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_stockmovement_reference'),
        ('receivables', '0001_initial'),
        ('tenancy', '0003_order_number_and_credit_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('agotado', 'Agotado'), ('stock_bajo', 'Stock bajo'), ('por_vencer', 'Por vencer'), ('fiado_vencido', 'Fiado vencido')], max_length=16, verbose_name='tipo')),
                ('message', models.TextField(verbose_name='mensaje')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='leída')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resuelta')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.barbershop')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='inventory.product')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.membership')),
                ('receivable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='receivables.receivable')),
            ],
            options={
                'indexes': [models.Index(fields=['barbershop', 'read_at', 'created_at'], name='alerts_aler_barbers_d599e2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('alert_type__in', ['agotado', 'stock_bajo', 'por_vencer', 'fiado_vencido'])), name='ck_alert_type_valid'), models.CheckConstraint(condition=models.Q(models.Q(('alert_type__in', ('agotado', 'stock_bajo', 'por_vencer')), ('product__isnull', False), ('receivable__isnull', True)), models.Q(('alert_type', 'fiado_vencido'), ('product__isnull', True), ('receivable__isnull', False)), _connector='OR'), name='ck_alert_reference_matches_type'), models.CheckConstraint(condition=models.Q(models.Q(('read_at__isnull', True), ('read_by__isnull', True)), models.Q(('read_at__isnull', False), ('read_by__isnull', False)), _connector='OR'), name='ck_alert_read_fields_together'), models.UniqueConstraint(condition=models.Q(('product__isnull', False), ('resolved_at__isnull', True)), fields=('alert_type', 'product'), name='uq_alert_open_per_product'), models.UniqueConstraint(condition=models.Q(('receivable__isnull', False), ('resolved_at__isnull', True)), fields=('alert_type', 'receivable'), name='uq_alert_open_per_receivable')],
            },
        ),
        EnableTenantRLS("alerts_alert"),
    ]
