# Generated by Django 6.1.2 on 2026-10-07 03:05

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

from apps.core.rls import EnableTenantRLS


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash', '0002_refund_kind'),
        ('catalog', '0001_initial'),
        ('clients', '0001_initial'),
        ('inventory', '0002_stockmovement_reference'),
        ('staff', '0001_initial'),
        ('tenancy', '0003_order_number_and_credit_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(editable=False, verbose_name='número')),
                ('status', models.CharField(choices=[('abierta', 'Abierta'), ('en_espera', 'En espera'), ('cerrada', 'Cerrada'), ('anulada', 'Anulada')], default='abierta', max_length=10, verbose_name='estado')),
                ('payment_status', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('fiado', 'Fiado')], default='pendiente', max_length=10, verbose_name='estado de pago')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='subtotal')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='descuento')),
                ('discount_reason', models.TextField(blank=True, verbose_name='motivo del descuento')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='total')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='pagado')),
                ('commission_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='comisiones')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='cerrada')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='anulada')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='motivo de anulación')),
                ('barber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='staff.barber')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.barbershop')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tenancy.branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='clients.client')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('servicio', 'Servicio'), ('producto', 'Producto')], max_length=10, verbose_name='tipo')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='cantidad')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='precio unitario')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='total de la línea')),
                ('line_discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='descuento repartido')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='costo unitario')),
                ('consumables_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='costo de insumos')),
                ('commission_type', models.CharField(blank=True, max_length=12, verbose_name='tipo de comisión')),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='valor de comisión')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='comisión')),
                ('barber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='staff.barber')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.barbershop')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='sales.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.product')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.service')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('efectivo', 'Efectivo'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('bre_b', 'Bre-B')], max_length=20, verbose_name='método')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='monto')),
                ('reference', models.CharField(blank=True, max_length=80, verbose_name='referencia')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.barbershop')),
                ('cash_movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale_payment', to='cash.cashmovement')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.order')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['barbershop', 'status', 'closed_at'], name='sales_order_barbers_5c8be3_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('barbershop', 'number'), name='uq_order_number_per_barbershop', violation_error_message='Ese número de comanda ya existe.'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['abierta', 'en_espera', 'cerrada', 'anulada'])), name='ck_order_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('payment_status__in', ['pendiente', 'pagado', 'fiado'])), name='ck_order_payment_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('discount__gte', 0), ('discount__lte', models.F('subtotal'))), name='ck_order_discount_within_subtotal', violation_error_message='El descuento no puede superar el subtotal.'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('discount', 0), models.Q(('discount_reason', ''), _negated=True), _connector='OR'), name='ck_order_discount_has_reason', violation_error_message='Un descuento necesita motivo.'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total', django.db.models.expressions.CombinedExpression(models.F('subtotal'), '-', models.F('discount')))), name='ck_order_total_adds_up'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0), ('amount_paid__lte', models.F('total'))), name='ck_order_paid_within_total', violation_error_message='Lo pagado no puede superar el total.'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'cerrada'), _negated=True), ('closed_at__isnull', False), _connector='OR'), name='ck_order_closed_has_date'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'anulada'), _negated=True), models.Q(('cancelled_at__isnull', False), models.Q(('cancel_reason', ''), _negated=True)), _connector='OR'), name='ck_order_cancelled_has_reason'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item_type', 'servicio'), ('product__isnull', True), ('service__isnull', False)), models.Q(('item_type', 'producto'), ('product__isnull', False), ('service__isnull', True)), _connector='OR'), name='ck_orderitem_one_reference_by_type'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_orderitem_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total', django.db.models.expressions.CombinedExpression(models.F('unit_price'), '*', models.F('quantity')))), name='ck_orderitem_line_total_adds_up'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_discount__gte', 0), ('line_discount__lte', models.F('line_total'))), name='ck_orderitem_discount_within_line'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('commission_amount__gte', 0)), name='ck_orderitem_commission_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('method__in', ['efectivo', 'nequi', 'daviplata', 'tarjeta', 'transferencia', 'bre_b'])), name='ck_payment_method_valid'),
        ),
        EnableTenantRLS("sales_order"),
        EnableTenantRLS("sales_orderitem"),
        EnableTenantRLS("sales_payment"),
    ]
