# Generated by Django 6.1.2 on 2026-10-06 19:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.core.rls import EnableTenantRLS


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Barbershop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trade_name",
                    models.CharField(max_length=120, verbose_name="nombre comercial"),
                ),
                (
                    "legal_name",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="razón social"
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="NIT o documento"
                    ),
                ),
                (
                    "tax_regime",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="régimen tributario"
                    ),
                ),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("timezone", models.CharField(default="America/Bogota", max_length=60)),
                ("currency", models.CharField(default="COP", max_length=3)),
                ("logo", models.ImageField(blank=True, upload_to="logos/")),
                (
                    "accent_color",
                    models.CharField(
                        default="#B08D57",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9A-Fa-f]{6}$",
                                "Usa un color hexadecimal, por ejemplo #B08D57.",
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Prueba"),
                            ("active", "Activa"),
                            ("suspended", "Suspendida"),
                            ("closed", "Cerrada"),
                        ],
                        default="trial",
                        max_length=12,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("address", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "barbershop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenancy.barbershop",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("barbershop", "name"),
                        name="uq_branch_name_per_barbershop",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Dueño"),
                            ("admin", "Administrador"),
                            ("cashier", "Cajero"),
                            ("barber", "Barbero"),
                            ("viewer", "Consultor"),
                        ],
                        max_length=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "barbershop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="tenancy.barbershop",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "barbershop"),
                        name="uq_membership_user_barbershop",
                    )
                ],
            },
        ),
        EnableTenantRLS("tenancy_branch"),
    ]
