# Generated by Django 6.1.2 on 2026-10-07 02:46

import apps.cash.choices
import django.contrib.postgres.fields
import django.contrib.postgres.validators
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models

from apps.core.rls import EnableTenantRLS


def create_settings_for_existing_barbershops(apps, schema_editor):
    """Corre antes de activar RLS, así el INSERT no necesita fijar cada barbería."""
    Barbershop = apps.get_model("tenancy", "Barbershop")
    BarbershopSettings = apps.get_model("tenancy", "BarbershopSettings")
    missing = Barbershop.objects.filter(settings__isnull=True)
    BarbershopSettings.objects.bulk_create(BarbershopSettings(barbershop=shop) for shop in missing)


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarbershopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vip_min_spent', models.DecimalField(decimal_places=2, default=Decimal('200000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='gasto mínimo VIP')),
                ('vip_min_visits', models.PositiveIntegerField(default=10, verbose_name='visitas mínimas VIP')),
                ('frequent_min_visits', models.PositiveIntegerField(default=3, verbose_name='visitas mínimas frecuente')),
                ('inactive_after_days', models.PositiveIntegerField(default=90, verbose_name='días sin visita para inactivo')),
                ('enabled_payment_methods', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('efectivo', 'Efectivo'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('bre_b', 'Bre-B')], max_length=20), default=apps.cash.choices.all_payment_methods, validators=[django.contrib.postgres.validators.ArrayMinLengthValidator(1)], verbose_name='métodos de pago habilitados')),
                ('barbershop', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settings', to='tenancy.barbershop')),
            ],
            options={
                'verbose_name': 'configuración de barbería',
            },
        ),
        migrations.RunPython(create_settings_for_existing_barbershops, migrations.RunPython.noop),
        EnableTenantRLS("tenancy_barbershopsettings"),
    ]
