# Generated by Django 6.1.2 on 2026-10-07 03:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_barbershop_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershopsettings',
            name='max_credit_per_client',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='crédito máximo por cliente'),
        ),
        migrations.AddField(
            model_name='barbershopsettings',
            name='next_order_number',
            field=models.PositiveIntegerField(default=1, verbose_name='siguiente número de comanda'),
        ),
    ]
