# Generated by Django 6.1.2 on 2026-10-07 03:06

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

from apps.core.rls import EnableTenantRLS


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash', '0002_refund_kind'),
        ('clients', '0001_initial'),
        ('sales', '0001_initial'),
        ('tenancy', '0003_order_number_and_credit_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='total')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='saldo')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido'), ('anulado', 'Anulado')], default='pendiente', max_length=10, verbose_name='estado')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='vence')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.barbershop')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='clients.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivable', to='sales.order')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivablePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='monto')),
                ('method', models.CharField(choices=[('efectivo', 'Efectivo'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('bre_b', 'Bre-B')], max_length=20, verbose_name='método')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.barbershop')),
                ('cash_movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receivable_payment', to='cash.cashmovement')),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='receivables.receivable')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['barbershop', 'status', 'due_date'], name='receivables_barbers_e3fdb1_idx'),
        ),
        migrations.AddConstraint(
            model_name='receivable',
            constraint=models.CheckConstraint(condition=models.Q(('total__gt', 0)), name='ck_receivable_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='receivable',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0), ('balance__lte', models.F('total'))), name='ck_receivable_balance_within_total', violation_error_message='El saldo no puede ser negativo ni mayor que el total.'),
        ),
        migrations.AddConstraint(
            model_name='receivable',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pendiente', 'pagado', 'vencido', 'anulado'])), name='ck_receivable_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='receivable',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'pagado'), _negated=True), ('balance', 0), _connector='OR'), name='ck_receivable_paid_has_no_balance'),
        ),
        migrations.AddConstraint(
            model_name='receivablepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_receivablepayment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='receivablepayment',
            constraint=models.CheckConstraint(condition=models.Q(('method__in', ['efectivo', 'nequi', 'daviplata', 'tarjeta', 'transferencia', 'bre_b'])), name='ck_receivablepayment_method_valid'),
        ),
        EnableTenantRLS("receivables_receivable"),
        EnableTenantRLS("receivables_receivablepayment"),
    ]
