# Generated by Django 6.1.2 on 2026-10-07 02:46

import apps.inventory.models
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

from apps.core.rls import EnableTenantRLS


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenancy', '0002_barbershop_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.barbershop')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('product_type', models.CharField(choices=[('venta', 'Venta'), ('consumible', 'Consumible interno'), ('perecedero', 'Perecedero')], max_length=12, verbose_name='tipo')),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='costo de compra')),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='precio de venta')),
                ('current_stock', models.IntegerField(default=0, editable=False, verbose_name='stock actual')),
                ('minimum_stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='stock mínimo')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='vence')),
                ('supplier', models.CharField(blank=True, max_length=120, verbose_name='proveedor')),
                ('photo', models.ImageField(blank=True, upload_to=apps.inventory.models.product_photo_path, verbose_name='foto')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.barbershop')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='cantidad')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.barbershop')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='inventory.product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumables', to='catalog.service')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('entrada', 'Entrada'), ('ajuste', 'Ajuste'), ('salida_venta', 'Salida por venta'), ('salida_servicio', 'Insumo de servicio'), ('reversion', 'Reversión')], max_length=16, verbose_name='tipo')),
                ('quantity', models.IntegerField(verbose_name='cantidad')),
                ('stock_before', models.IntegerField(verbose_name='stock antes')),
                ('stock_after', models.IntegerField(verbose_name='stock después')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='costo unitario')),
                ('reason', models.TextField(verbose_name='motivo')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.barbershop')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(models.F('barbershop'), django.db.models.functions.text.Lower('name'), condition=models.Q(('deleted_at__isnull', True)), name='uq_productcategory_name_per_barbershop', violation_error_message='Ya existe una categoría con ese nombre.'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(models.F('barbershop'), django.db.models.functions.text.Lower('name'), condition=models.Q(('deleted_at__isnull', True)), name='uq_product_name_per_barbershop', violation_error_message='Ya existe un producto con ese nombre.'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('current_stock__gte', 0)), name='ck_product_stock_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_cost__gte', 0)), name='ck_product_cost_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__gte', 0)), name='ck_product_price_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('product_type__in', ['venta', 'consumible', 'perecedero'])), name='ck_product_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='serviceconsumable',
            constraint=models.UniqueConstraint(fields=('service', 'product'), name='uq_serviceconsumable_service_product', violation_error_message='Ese producto ya es insumo del servicio.'),
        ),
        migrations.AddConstraint(
            model_name='serviceconsumable',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_serviceconsumable_quantity_positive'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'created_at'], name='inventory_s_product_5919a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='ck_stockmovement_quantity_not_zero'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('stock_after__gte', 0)), name='ck_stockmovement_stock_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('stock_after', django.db.models.expressions.CombinedExpression(models.F('stock_before'), '+', models.F('quantity')))), name='ck_stockmovement_stock_adds_up'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='ck_stockmovement_reason_present'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('movement_type__in', ['entrada', 'ajuste', 'salida_venta', 'salida_servicio', 'reversion'])), name='ck_stockmovement_type_valid'),
        ),
        EnableTenantRLS("inventory_productcategory"),
        EnableTenantRLS("inventory_product"),
        EnableTenantRLS("inventory_stockmovement"),
        EnableTenantRLS("inventory_serviceconsumable"),
    ]
