# Generated by Django 6.1.2 on 2026-10-07 02:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from apps.core.rls import EnableTenantRLS


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_barbershop_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=120, verbose_name='nombre completo')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('document_number_encrypted', models.TextField(blank=True, editable=False)),
                ('document_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('data_consent_at', models.DateTimeField(verbose_name='autorización de datos')),
                ('data_policy_version', models.CharField(max_length=20, verbose_name='versión de la política de datos')),
                ('name_key', models.CharField(blank=True, editable=False, max_length=120)),
                ('anonymized_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='anonimizado')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.barbershop')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['barbershop', 'name_key'], name='ix_client_name_key')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('document_hash', ''), _negated=True)), fields=('barbershop', 'document_hash'), name='uq_client_document_per_barbershop', violation_error_message='Ya existe un cliente con ese documento.'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('phone', ''), _negated=True)), fields=('barbershop', 'phone'), name='uq_client_phone_per_barbershop', violation_error_message='Ya existe un cliente con ese teléfono.'), models.CheckConstraint(condition=models.Q(('data_policy_version', ''), _negated=True), name='ck_client_policy_version_present')],
            },
        ),
        EnableTenantRLS("clients_client"),
    ]
