# Generated by Django 6.1.2 on 2026-10-07 02:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

from apps.core.rls import EnableTenantRLS


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_barbershop_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='abierta')),
                ('opening_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='base')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='cerrada')),
                ('counted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='efectivo contado')),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='efectivo esperado')),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='diferencia')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.barbershop')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to='tenancy.branch')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('venta', 'Venta'), ('abono_fiado', 'Abono de fiado'), ('ingreso_manual', 'Ingreso manual'), ('gasto', 'Gasto'), ('retiro', 'Retiro'), ('ajuste', 'Ajuste')], max_length=16, verbose_name='tipo')),
                ('direction', models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida')], max_length=3, verbose_name='sentido')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='monto')),
                ('payment_method', models.CharField(choices=[('efectivo', 'Efectivo'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('bre_b', 'Bre-B')], max_length=20, verbose_name='método de pago')),
                ('description', models.TextField(verbose_name='descripción')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.barbershop')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='cash.cashsession')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True)), fields=('barbershop', 'branch'), name='uq_cashsession_one_open_per_branch', violation_error_message='Ya hay una caja abierta en esta sede.'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.CheckConstraint(condition=models.Q(('opening_amount__gte', 0)), name='ck_cashsession_opening_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.CheckConstraint(condition=models.Q(('counted_amount__isnull', True), ('counted_amount__gte', 0), _connector='OR'), name='ck_cashsession_counted_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', True), ('closed_by__isnull', True), ('counted_amount__isnull', True), ('difference__isnull', True), ('expected_amount__isnull', True)), models.Q(('closed_at__isnull', False), ('closed_by__isnull', False), ('counted_amount__isnull', False), ('difference__isnull', False), ('expected_amount__isnull', False)), _connector='OR'), name='ck_cashsession_close_fields_together'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['session', 'payment_method'], name='cash_cashmo_session_cadd06_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_cashmovement_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(('description', ''), _negated=True), name='ck_cashmovement_description_present'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['venta', 'abono_fiado', 'ingreso_manual', 'gasto', 'retiro', 'ajuste'])), name='ck_cashmovement_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(('payment_method__in', ['efectivo', 'nequi', 'daviplata', 'tarjeta', 'transferencia', 'bre_b'])), name='ck_cashmovement_method_valid'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('direction', 'in'), ('kind__in', ('venta', 'abono_fiado', 'ingreso_manual'))), models.Q(('direction', 'out'), ('kind__in', ('gasto', 'retiro'))), models.Q(('direction__in', ['in', 'out']), ('kind', 'ajuste')), _connector='OR'), name='ck_cashmovement_kind_matches_direction'),
        ),
        EnableTenantRLS("cash_cashsession"),
        EnableTenantRLS("cash_cashmovement"),
    ]
