# Generated by Django 6.1.2 on 2026-10-07 03:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
        ('tenancy', '0003_order_number_and_credit_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cashmovement',
            name='ck_cashmovement_kind_valid',
        ),
        migrations.RemoveConstraint(
            model_name='cashmovement',
            name='ck_cashmovement_kind_matches_direction',
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='kind',
            field=models.CharField(choices=[('venta', 'Venta'), ('abono_fiado', 'Abono de fiado'), ('ingreso_manual', 'Ingreso manual'), ('gasto', 'Gasto'), ('retiro', 'Retiro'), ('ajuste', 'Ajuste'), ('devolucion', 'Devolución')], max_length=16, verbose_name='tipo'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['venta', 'abono_fiado', 'ingreso_manual', 'gasto', 'retiro', 'ajuste', 'devolucion'])), name='ck_cashmovement_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('direction', 'in'), ('kind__in', ('venta', 'abono_fiado', 'ingreso_manual'))), models.Q(('direction', 'out'), ('kind__in', ('gasto', 'retiro', 'devolucion'))), models.Q(('direction__in', ['in', 'out']), ('kind', 'ajuste')), _connector='OR'), name='ck_cashmovement_kind_matches_direction'),
        ),
    ]
